### PR TITLE
Correct fork owner name

### PR DESCRIPTION
**Pull request by l3ender**
### What does this PR do?
Updates the documentation for the correct repo owner name.

### What testing has been done on this change?
Documentation change only.

### CODE REVIEW

**Comment by l3ender** [comment]
@maksim-sakki Your fork of this plugin looks like the most active one and we'd like to join on and help contribute as we are wanting an updated version as well. Would you be agreeable to others collaborating on your fork?

Here's a small change to correct documentation for the repo owner name.

Thanks!

**Comment by asolntsev** [comment]
@l3ender Thank you for the contribution. Merged.

**Comment by l3ender** [comment]
@asolntsev Thanks for the merge!

A few related questions:
1. Could you publish tags for versions? This allows people to add npm dependencies to a specific commit more clearly instead of targeting a branch name.
2. Would you be willing to enable issues on this repo so that if any things come up where we plan to make changes, we can track them appropriately? Also if there are any questions this would be the easiest way to collaborate.

**Comment by asolntsev** [comment]
@l3ender Sure.
1. I created tags `3.2.0` and `3.1.0-cb2` for last two releases.
2. I have enabled issues.

**Pull request merged**
